title: Learning-based Compression and <br />Compressed Domain Analysis<br />in Remote Sensing 
baseurl: ""
url: https://compression.rsim.berlin
description: >- # this means to ignore newlines until next key
  Learning-based Compression and Compressed Domain Analysis in Remote Sensing 
short_description: >-
  Learning-based Compression and Compressed Domain Analysis in Remote Sensing 
collections_dir: content
collections:
  software:
    output: true
  publications:
    output: true